### ISSUE TITLE
Add articles to the research page in PDF format

### ISSUE THREAD

**Issue by JRud52** [xTVaser/it-group-project#2]
Add links to the fake research papers we made to the research page. They should be in PDF format so that the viewer can read them right in the browser.

**Comment by xTVaser** [comment]
Research pdfs have been added as of 34a2a9cb9298768a5c6aa8d5b000b20e89b84cc5

I was thinking of just having links with the article name that link to the pdf.

**Comment by xTVaser** [comment]
More papers can be made here https://pdos.csail.mit.edu/archive/scigen/

**Comment by JRud52** [comment]
just added the links
